<?php

namespace Entity\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityRoleResourceProxy extends \Entity\RoleResource implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getRole()
    {
        $this->_load();
        return parent::getRole();
    }

    public function setRole(\Entity\Role $role)
    {
        $this->_load();
        return parent::setRole($role);
    }

    public function getResource()
    {
        $this->_load();
        return parent::getResource();
    }

    public function setResource(\Entity\Resource $resource)
    {
        $this->_load();
        return parent::setResource($resource);
    }

    public function getPrivilege()
    {
        $this->_load();
        return parent::getPrivilege();
    }

    public function setPrivilege($privilege)
    {
        $this->_load();
        return parent::setPrivilege($privilege);
    }

    public function accept(\Equ\EntityVisitor $visitor)
    {
        $this->_load();
        return parent::accept($visitor);
    }

    public function getFieldValidators()
    {
        $this->_load();
        return parent::getFieldValidators();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'role', 'resource', 'privilege');
    }
}