<?php

namespace Entity\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityResourceProxy extends \Entity\Resource implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getParent()
    {
        $this->_load();
        return parent::getParent();
    }

    public function setParent(\Entity\Resource $parent)
    {
        $this->_load();
        return parent::setParent($parent);
    }

    public function getRoleResources()
    {
        $this->_load();
        return parent::getRoleResources();
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }

    public function accept(\Equ\EntityVisitor $visitor)
    {
        $this->_load();
        return parent::accept($visitor);
    }

    public function getFieldValidators()
    {
        $this->_load();
        return parent::getFieldValidators();
    }

    public function getResourceId()
    {
        $this->_load();
        return parent::getResourceId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'parent', 'children', 'lft', 'rgt', 'lvl', 'roleResources');
    }
}