<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="description" content="EquCMS" />
<meta name="keywords" content="equcms" />
<meta name="revisit-after" content="3 days" />
<meta name="robots" content="all" />
<meta name="author" content="Szurovecz János" />
<meta name="distribution" content="Global" />
<meta name="rating" content="General" />
<meta name="doc-type" content="Web Page" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php $this->headScript()->captureStart() ?>
  $(document).ready(function() {
    $("#mainMenu ul.navigation > li > a").click(function() {
      $(this).attr('href', '#');
      $(this).parent().toggleClass('open');
    });
  });
<?php $this->headScript()->captureEnd() ?>
<?php
  $this->dojo()
    ->setDjConfigOption('usePlainJson',true)
    ->setDjConfigOption('locale', Zend_Controller_Front::getInstance()->getRequest()->getParam('lang'))
    ->addStylesheetModule('dijit.themes.claro')
    ->setCdnBase(Zend_Dojo::CDN_BASE_GOOGLE)
    ->setCdnVersion('1.5')
    ->requireModule('dojo.i18n');
  echo $this->dojo();
?>
<?php
  $this->headScript()
    ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js', 'text/javascript');
  $this->headLink()
    ->appendStylesheet($this->baseUrl('/styleSheets/reset.css'))
    ->appendStylesheet($this->baseUrl('/styleSheets/960.css'))
    ->appendStylesheet($this->baseUrl('/styleSheets/crud.css'))
    ->appendStylesheet($this->baseUrl('/styleSheets/style.css'));
  echo 
    $this->headTitle('EquCMS')->setSeparator(' - ') .
    $this->headLink() .
    $this->headStyle() .
    $this->headScript();

  $mainMenuItem = $this->navigation()->findById('index_admin');
?>
</head>
<body class="claro">
	<div id="page">
    <div class="container_12">
      <div class="container_12">
        <div class="grid_12" id="head">
        	<div id="logo" class="grid_3">
            <h1>EquCMS</h1>
          </div>
      	</div>
      </div>
      <div class="grid_3" id="mainMenu">
        <?php echo $this->navigation()->menu()->renderMenu($mainMenuItem, array('minDepth' => 0, 'maxDepth' => 1)) ?>
      </div>
      <div class="grid_9">
      	<div id="breadcrumbs">
      	  <?php echo $this->navigation()->breadcrumbs()->setSeparator(' &raquo; ')->render($mainMenuItem) ?>
      	</div>
      	<div id="submenu">
      		<?php echo $this->navigation()->menu()->renderMenu($mainMenuItem, array('onlyActiveBranch' => true, 'renderParents' => false)) ?>
      	</div>
        <div class="clear"></div>
      	<?php echo $this->flashMessenger() ?>
        <?php print $this->layout()->content ?>
      </div>
    </div>
    <div class="clear"></div>
    <div class="container_12" id="poweredby">
    </div>
  </div>
</body>
</html>