<?php echo $this->doctype() ?>
<html>
<head>
<meta name="description" content="EquCMS" />
<meta name="keywords" content="equcms" />
<meta name="revisit-after" content="3 days" />
<meta name="robots" content="all" />
<meta name="author" content="Szurovecz János" />
<meta name="rating" content="General" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php
  $this->headScript()
    ->prependFile('/js/bootstrap.min.js', 'text/javascript')
    ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js', 'text/javascript');
  $this->headLink()
    ->appendStylesheet($this->baseUrl('/css/bootstrap.min.css'))
    ->appendStylesheet($this->baseUrl('/css/bootstrap-responsive.min.css'))
    ->appendStylesheet($this->baseUrl('/styleSheets/ownBootstrap.css'));
  echo 
    $this->headTitle('EquCMS')->setSeparator(' - ') .
    $this->headLink() .
    $this->headStyle();

  $mainMenuItem = $this->navigation()->findById('index_index');
?>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a href="/" class="brand" title="EquCMS">EquCMS</a>
            <div class="nav-collapse">
              <?php echo $this->navigation()->menu()->renderMenu($mainMenuItem, array('minDepth' => 0, 'maxDepth' => 0, 'ulClass' => 'nav span7')) ?>
              <ul class="nav pull-right">
                <?php if ($this->authenticatedUser->isLoggedIn()): ?>
                <li>
                  <a href="#"><i class="icon-user icon-white"></i> <?php echo $this->authenticatedUser->getRoleId() ?></a>
                </li>
                <li>
                  <a title="Logout" href="<?php echo $this->url(array('module' => 'user', 'controller' => 'index', 'action' => 'logout'), 'defaultlang') ?>">
                    <i class="icon-off icon-white"></i> Logout
                  </a>
                </li>
                <?php else: ?>
                <li>
                  <a title="Login" href="<?php echo $this->url(array('module' => 'user', 'controller' => 'index', 'action' => 'login'), 'defaultlang') ?>">
                    Login
                  </a>
                </li>
                <?php endif ?>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="subnav subnav-fixed">
        <?php echo $this->navigation()->menu()->renderMenu($mainMenuItem, array('onlyActiveBranch' => true, 'renderParents' => false, 'ulClass' => 'nav nav-pills')) ?>
      </div>
    </div>
    <div class="row" id="page">
      <div class="span12">
      	<?php echo $this->flashMessenger() ?>
        <?php print $this->layout()->content ?>
      </div>
      <div class="container_12" id="poweredby"></div>
    </div>
  </div>
  <?php echo $this->headScript(); ?>
</body>
</html>