<h2><?php echo $this->translate($this->pageTitle) ?></h2>
<table>
  <tr>
    <?php foreach ($this->keys as $key): ?>
      <th><a href="<?php echo $this->url(array('order' => $this->nextOrder, 'sort' => $key)) ?>"><?php echo $key ?></a></th>
    <?php endforeach ?>
    <th><?php echo $this->translate('Crud/Methods') ?></th>
  </tr>
  <?php foreach ($this->paginator as $record): ?>
    <tr>
      <?php foreach ($this->keys as $key): ?>
        <td>
        <?php
        if ($key == 'allowed') {
          echo $record->isAllowed() ? $this->translate('Crud/True') : $this->translate('Crud/False');
        } else {
          $field = $record[$key];
          if (is_bool($field)) {
            echo $field ? $this->translate('Crud/True') : $this->translate('Crud/False');
          } elseif (is_object($field)) {
            echo (string)$field;
          }
          else {
            echo $field;
          }
        }
        ?>
        </td>
      <?php endforeach ?>
      <td>
        <div class="methods-list">
          <a href="<?php echo $this->url(array('action' => 'update', 'id' => $record->getId())) ?>"><?php echo $this->translate('Crud/Update/Label') ?></a>
          | <a onclick="javascript: return confirm('<?php echo $this->translate('Crud/Delete/Confirm')?>')" href="<?php echo $this->url(array('action' => 'delete', 'id' => $record->getId())) ?>"><?php echo $this->translate('Crud/Delete/Label') ?></a>
        </div>
      </td>
    </tr>
  <?php endforeach ?>
</table>
<div class="paginator">
  <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>