<?php

namespace entities\Proxy\__CG__\entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Mvc extends \entities\Mvc implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getModule()
    {
        $this->__load();
        return parent::getModule();
    }

    public function setModule($module)
    {
        $this->__load();
        return parent::setModule($module);
    }

    public function getController()
    {
        $this->__load();
        return parent::getController();
    }

    public function setController($controller)
    {
        $this->__load();
        return parent::setController($controller);
    }

    public function getAction()
    {
        $this->__load();
        return parent::getAction();
    }

    public function setAction($action)
    {
        $this->__load();
        return parent::setAction($action);
    }

    public function getNavigationPage($refresh = false)
    {
        $this->__load();
        return parent::getNavigationPage($refresh);
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($serialized)
    {
        $this->__load();
        return parent::unserialize($serialized);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent(\entities\Resource $parent = NULL)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getRoleResources()
    {
        $this->__load();
        return parent::getRoleResources();
    }

    public function getResourceId()
    {
        $this->__load();
        return parent::getResourceId();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setValidator(\Equ\Object\Validator $validator)
    {
        $this->__load();
        return parent::setValidator($validator);
    }

    public function getValidator()
    {
        $this->__load();
        return parent::getValidator();
    }

    public function validate()
    {
        $this->__load();
        return parent::validate();
    }

    public function offsetExists($offset)
    {
        $this->__load();
        return parent::offsetExists($offset);
    }

    public function offsetGet($offset)
    {
        $this->__load();
        return parent::offsetGet($offset);
    }

    public function offsetSet($offset, $value)
    {
        $this->__load();
        return parent::offsetSet($offset, $value);
    }

    public function offsetUnset($offset)
    {
        $this->__load();
        return parent::offsetUnset($offset);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'lft', 'rgt', 'lvl', 'resource', 'parent', 'children', 'roleResources', 'module', 'controller', 'action');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}