<?php

namespace entities\Proxy\__CG__\entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getPrincipal()
    {
        $this->__load();
        return parent::getPrincipal();
    }

    public function initActivationCode()
    {
        $this->__load();
        return parent::initActivationCode();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getPasswordHash()
    {
        $this->__load();
        return parent::getPasswordHash();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getActivationCode()
    {
        $this->__load();
        return parent::getActivationCode();
    }

    public function setActivationCode($activationCode)
    {
        $this->__load();
        return parent::setActivationCode($activationCode);
    }

    public function isLoggedIn()
    {
        $this->__load();
        return parent::isLoggedIn();
    }

    public function setLoggedIn($loggedIn = true)
    {
        $this->__load();
        return parent::setLoggedIn($loggedIn);
    }

    public function getRoleId()
    {
        $this->__load();
        return parent::getRoleId();
    }

    public function getUserGroup()
    {
        $this->__load();
        return parent::getUserGroup();
    }

    public function setUserGroup(\entities\UserGroup $group)
    {
        $this->__load();
        return parent::setUserGroup($group);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function setValidator(\Equ\Object\Validator $validator)
    {
        $this->__load();
        return parent::setValidator($validator);
    }

    public function getValidator()
    {
        $this->__load();
        return parent::getValidator();
    }

    public function validate()
    {
        $this->__load();
        return parent::validate();
    }

    public function offsetExists($offset)
    {
        $this->__load();
        return parent::offsetExists($offset);
    }

    public function offsetGet($offset)
    {
        $this->__load();
        return parent::offsetGet($offset);
    }

    public function offsetSet($offset, $value)
    {
        $this->__load();
        return parent::offsetSet($offset, $value);
    }

    public function offsetUnset($offset)
    {
        $this->__load();
        return parent::offsetUnset($offset);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'email', 'passwordHash', 'activationCode', 'userGroup');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}