<div class="hero-unit">
  <h1><?php echo $this->translate($this->message) ?></h1>
  <p></p>
  <p><?php echo $this->translate('Sorry, but the page you are looking for has not been found.<br>Try checking the URL for errors, then hit the refresh button on your browser.') ?></p>
  <p>
    <a class="btn btn-primary btn-large" href="<?php echo $this->url(array(), 'defaultlang', true) ?>">
      <?php echo $this->translate('Go to the main page') ?>
    </a>
  </p>
</div>  

<?php if (isset($this->exception)): ?>

<h3>Exception information:</h3>
<p>
    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?>
</pre>
<?php endif ?>
